# Generated by Django 3.0.2 on 2020-05-14 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adressverwaltung', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='housenumber',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='person',
            name='zipCode',
            field=models.IntegerField(),
        ),
    ]
